spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    url: ${JDBC_DATABASE_URL}
    user: ${JDBC_DATABASE_USER}
    password: ${JDBC_DATABASE_PASSWORD}
    locations: classpath:db/migration
    enabled: true
