spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    url: ${DATABASE_URL}
    user: $DATABASE_URL["user"]
    password: $DATABASE_URL["pass"]
    locations: classpath:db/migration
