spring:
  datasource:
    url: ${DATABASE_URL}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  profiles:
    active: ${SPRING_PROFILE}
flyway:
  locations: classpath=db/migration
