spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/account_manager
    username: account_manager_user
    password: account_manager_password
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        format_sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/account_manager
    user: account_manager_user
    password: account_manager_password
    locations: classpath:db/migration
logging:
  level:
    web: info
server:
  port: 8080