spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: ${DATASOURCE_DRIVER_CLASSNAME}
    hikari:
      connection-timeout: ${TIMEOUT:20000}
      maximum-pool-size: ${MAXIMUM_PULL_SIZE:5}
  jpa:
    database-platform: ${DATABASE_PLATFORM}
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT}
        format_sql: false
server:
  port: ${SERVER_PORT}
